version: "3.9"
services:
  neo4j:
    image: neo4j:community-ubi9
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      NEO4J_AUTH: neo4j/your_password
volumes:
  neo4j_data:
  neo4j_logs: